### ISSUE TITLE
Scripting cargo ships

### ISSUE THREAD

**Issue by ThatOneBepis** [ThatOneBepis/Infinitodustry-legacy#45]

**Comment by deltanedas** [comment]
more info its probably possible

**Comment by ThatOneBepis** [comment]
Info: can pick up and unload units with a special hotkey (ie. P and L, unless used already). Can pick up units, as long as it's Cargo Capacity is higher than sum of Cargo Size of all units present. plus Cargo Size of the units what will be picked up.

**Comment by ThatOneBepis** [comment]
6.0 is going to make this in a way
