### ISSUE TITLE
Missing a file

### ISSUE THREAD

**Issue by Seraphina42** [ThatOneBepis/Infinitodustry-legacy#68]
I have tried to download this mod several times but every time I try and enable the mod it says that I am getting and error with the infinitodustry-angel file. I do not know how to fix this issue and as far as I can tell this file does not exist in my mod files.
![Capture](https://user-images.githubusercontent.com/59005013/82394256-918b3980-9a16-11ea-844c-fc7a00faaf13.JPG)
![Capture2](https://user-images.githubusercontent.com/59005013/82394343-c6978c00-9a16-11ea-854d-47e57e034856.JPG)
Any help would be appreciated.

**Comment by ThatOneBepis** [comment]
sorry my bad
working on fixing it

**Comment by Seraphina42** [comment]
is coming across as a issue for a lot of people?

**Comment by ThatOneBepis** [comment]
hoping this will fix it
https://github.com/ThatOneBepis/Infinitodustry/commit/ac64cb86dc9d083804b5289100cb364928d374f6

**Comment by Seraphina42** [comment]
Thank you that seems to have fixed it thanks. Also I really love your mod.
